### ISSUE TITLE
scss-linter config should be configurable

### ISSUE THREAD

**Issue by Arjen-Smit** [ConnectHolland/gulp-tasks#26]
You should be able to apply a different rule set to the scss-linter.
In my opinion there should be 3 options to set this file ordered by priority

1: add a path to the config to the config.json
2: look in the project folder if there is a config
3: use the included config

**Comment by ahoek** [comment]
Looks OK to me. Do you mean var/frontend in the project folder?

**Comment by Arjen-Smit** [comment]
The project folder is the folder where gulp is run from ( in our case that would most likely be var/frontend )
