### ISSUE TITLE
Add warning for non-existing files

### ISSUE THREAD

**Issue by gisostallenberg** [ConnectHolland/gulp-tasks#3]

**Comment by Arjen-Smit** [comment]
gulp by default ignores missing files, so a task could be created to do a file check. maybe this can be combined with a task to do a plugin check so the user can be notified of missing files and or plugins.

**Comment by gisostallenberg** [comment]
Maybe you can provide some more info on how I would do this, then I'm happy to create a pull request

**Comment by gisostallenberg** [comment]
This issue is stale
